### PR TITLE
fix: solves eth_createAccessList unmarshaling error

### LINKED ISSUE #520: Unmarshalling error on eth_createAccessList
#### System information

Op-Geth version: `v1.101500.0`
Op-Node version: v1.11.1
OS & Version: Linux

We encountered an unmarshaling error when running `eth_createAccessList` JSON-RPC queries on op-geth:

```
~ curl -X POST http://localhost:8545 -H "Content-Type: application/json"
 -d '{"method":"eth_createAccessList","params":[{"accessList":[],"data":"0x095ea7b3000000000000000000000000f2c38de50a250c0060fb45ebe4504b67f6f1be3c000000000000000000000000000000000000000000000000aac1d6a641344d81","from":"0xc631cb3a480bec80e9b8894894ddd6ddd4ea5612","maxFeePerGas":"0x2459a7","maxPriorityFeePerGas":"0x0","to":"0x26029ed89a19b919b5698f10cf776a4f4aea1529","type":"0x02"},"latest"],"id":45940,"jsonrpc":"2.0"}'

{"jsonrpc":"2.0","id":45940,"error":{"code":-32602,"message":"invalid argument 1: json: cannot unmarshal string into Go value of type state.StateDB"}}
```

While the same query ran against a `v1.101411.6` op-geth client fails correctly due to insufficient funds:

```
curl -X POST http://localhost:8545 -H "Content-Type: application/json" 
-d '{"method":"eth_createAccessList","params":[{"accessList":[],"data":"0x095ea7b3000000000000000000000000f2c38de50a250c0060fb45ebe4504b67f6f1be3c000000000000000000000000000000000000000000000000aac1d6a641344d81","from":"0xc631cb3a480bec80e9b8894894ddd6ddd4ea5612","maxFeePerGas":"0x2459a7","maxPriorityFeePerGas":"0x0","to":"0x26029ed89a19b919b5698f10cf776a4f4aea1529","type":"0x02"},"latest"],"id":45940,"jsonrpc":"2.0"}'

{"jsonrpc":"2.0","id":45940,"error":{"code":-32000,"message":"failed to apply transaction: 0x8996b0f7f8dd4484cb937b0f49c027d3ab7cc898d2a46eb297295769d9d1260b err: insufficient funds for gas * price + value: address 0xC631Cb3A480bEC80E9b8894894Ddd6ddD4EA5612 have 0 want 714674100000000"}}
```

This was tested against op-geth clients running on the Optimism Mainnet, Optimism Sepolia, Base Mainnet and Base Sepolia networks with the exact same behaviour.

Here are the arguments we are using:
```
    - --datadir=/data
    - --networkid=11155420
    - --op-network=op-sepolia
    - --port=30300
    - --http
    - --http.addr=0.0.0.0
    - --http.vhosts=*
    - --http.corsdomain=*
    - --http.port=8545
    - --http.api=web3,debug,eth,txpool,net,engine
    - --ws
    - --ws.addr=0.0.0.0
    - --ws.port=8546
    - --ws.api=web3,debug,eth,txpool,net,engine
    - --ws.origins=*
    - --graphql
    - --graphql.vhosts=*
    - --graphql.corsdomain=*
    - --syncmode=full
    - --nodiscover
    - --maxpeers=1
    - --gcmode=archive
    - --rollup.disabletxpoolgossip=true
    - --rollup.sequencerhttp=https://sepolia-sequencer.optimism.io
    - --authrpc.addr=127.0.0.1
    - --authrpc.port=8551
    - --authrpc.vhosts=*
    - --authrpc.jwtsecret=/tmp/op/jwt-secret.txt
    - --cache=8192
    - --rpc.gascap=300000000
    - --metrics
    - --metrics.addr=0.0.0.0
    - --metrics.port=9090
```
We are using the exact same arguments in all our op-geth instances, except for the `networkid` and `op-network` arguments, which vary by network.

### PR DESCRIPTION
**Pull request by sebaespindola**
**Description**

Solves [#520](https://github.com/ethereum-optimism/op-geth/issues/520).

This is a fix for the unmarshaling error that was encountered on version 1.101500.0
The signature of the `CreateAccessList` method was modified and the state was removed.

**Tests**
The tests were executed and they have the same results as in the optimism branch.

**Additional context**

**Metadata**

Fixes #520

### CODE REVIEW

File: internal/ethapi/api.go [hunk 1]
```diff
@@ -1297,7 +1297,7 @@ func (api *BlockChainAPI) CreateAccessList(ctx context.Context, args Transaction
 		}
 	}
 
-	acl, gasUsed, vmerr, err := AccessList(ctx, api.b, bNrOrHash, args, state)
+	acl, gasUsed, vmerr, err := AccessList(ctx, api.b, bNrOrHash, args, nil)
```
Comment (protolambda) [inline internal/ethapi/api.go]: Please explain the change. This does not seem right. The access-list construction requires the state-DB.

**Review by protolambda — CHANGES_REQUESTED** [review]

File: internal/ethapi/api.go (hunk 1 above)
Comment (sebaespindola) [reply internal/ethapi/api.go]: You are correct, I added a call to get the state inside the function and removed the null in the AccessList call

**Comment by sebaespindola** [comment]
I had previously replaced the state in the `AccessList` method call with a nil by mistake.
I'm getting the state with a call to `StateAndHeaderByNumberOrHash` and passing it back to `AccessList` now.

**Comment by sebaespindola** [comment]
@protolambda sorry to bother you, but if you could review again this PR when you have some time, that would be great.
The nulification of the state in the `CreateAccessList` method that you noted and requested changes is now fixed.

Thanks!

**Review by protolambda — DISMISSED** [review]

**Comment by protolambda** [comment]
Upon closer inspection the original `headerByNumberOrHash` call was turning generic errors in `ethereum.NotFound` for API purposes. I changed it to preserve that behavior.
And the `AccessList` method itself was already retrieving the state, so there is no point in retrieving the state twice.

Updated the PR to fix these. We can squash-merge the results to cleanup the git history churn.

cc @sebastianst for review of these new changes.

**Review by sebastianst — APPROVED** [review]
