### PR TITLE
eth/downloader: Fix deposit receipt correction

### LINKED ISSUE #679: Receipt Correction: Failed to decode RLP receipts ( v1.101602.0 )
#### System information

Geth version: v1.101602.0
CL client & version: op-node v1.13.6
OS & Version: Ubuntu host with Docker
Commit hash : (if `develop`)

Network: op-mainnet during full sync

#### Expected behaviour

Should not crash with Receipt Correction error during sync

#### Actual behaviour

```
 WARN [09-12|12:12:29.712] Receipt Correction: Failed to decode RLP receipts err="rlp: expected input string or byte for types.Bloom, decoding into (types.Receipts)[0](types.receiptRLP).Bloom"
 WARN [09-12|12:12:29.712] Receipt Correction: Failed to decode RLP receipts err="rlp: expected input string or byte for types.Bloom, decoding into (types.Receipts)[0](types.receiptRLP).Bloom"
 WARN [09-12|12:12:29.712] Receipt Correction: Failed to decode RLP receipts err="rlp: expected input string or byte for types.Bloom, decoding into (types.Receipts)[0](types.receiptRLP).Bloom"
 WARN [09-12|12:12:29.712] Receipt Correction: Failed to decode RLP receipts err="rlp: expected input string or byte for types.Bloom, decoding into (types.Receipts)[0](types.receiptRLP).Bloom"
 WARN [09-12|12:12:29.712] Receipt Correction: Failed to decode RLP receipts err="rlp: expected input string or byte for types.Bloom, decoding into (types.Receipts)[0](types.receiptRLP).Bloom"
 WARN [09-12|12:12:29.712] Receipt Correction: Failed to decode RLP receipts err="rlp: expected input string or byte for types.Bloom, decoding into (types.Receipts)[0](types.receiptRLP).Bloom"
 WARN [09-12|12:12:29.712] Receipt Correction: Failed to decode RLP receipts err="rlp: expected input string or byte for types.Bloom, decoding into (types.Receipts)[0](types.receiptRLP).Bloom"
 WARN [09-12|12:12:29.712] Receipt Correction: Failed to decode RLP receipts err="rlp: expected input string or byte for types.Bloom, decoding into (types.Receipts)[0](types.receiptRLP).Bloom"
 WARN [09-12|12:12:29.712] Receipt Correction: Failed to decode RLP receipts err="rlp: expected input string or byte for types.Bloom, decoding into (types.Receipts)[0](types.receiptRLP).Bloom"
 WARN [09-12|12:12:29.712] Receipt Correction: Failed to decode RLP receipts err="rlp: expected input string or byte for types.Bloom, decoding into (types.Receipts)[0](types.receiptRLP).Bloom"
 WARN [09-12|12:12:29.712] Receipt Correction: Failed to decode RLP receipts err="rlp: expected input string or byte for types.Bloom, decoding into (types.Receipts)[0](types.receiptRLP).Bloom"
 WARN [09-12|12:12:29.712] Receipt Correction: Failed to decode RLP receipts err="rlp: expected input string or byte for types.Bloom, decoding into (types.Receipts)[0](types.receiptRLP).Bloom"
 WARN [09-12|12:12:29.712] Receipt Correction: Failed to decode RLP receipts err="rlp: expected input string or byte for types.Bloom, decoding into (types.Receipts)[0](types.receiptRLP).Bloom"
 WARN [09-12|12:12:29.712] Receipt Correction: Failed to decode RLP receipts err="rlp: expected input string or byte for types.Bloom, decoding into (types.Receipts)[0](types.receiptRLP).Bloom"
 WARN [09-12|12:12:29.712] Receipt Correction: Failed to decode RLP receipts err="rlp: expected input string or byte for types.Bloom, decoding into (types.Receipts)[0](types.receiptRLP).Bloom"
 WARN [09-12|12:12:29.712] Receipt Correction: Failed to decode RLP receipts err="rlp: expected input string or byte for types.Bloom, decoding into (types.Receipts)[0](types.receiptRLP).Bloom"
 WARN [09-12|12:12:29.712] Receipt Correction: Failed to decode RLP receipts err="rlp: expected input string or byte for types.Bloom, decoding into (types.Receipts)[0](types.receiptRLP).Bloom"
 WARN [09-12|12:12:29.712] Receipt Correction: Failed to decode RLP receipts err="rlp: expected input string or byte for types.Bloom, decoding into (types.Receipts)[0](types.receiptRLP).Bloom"
 WARN [09-12|12:12:29.712] Receipt Correction: Failed to decode RLP receipts err="rlp: expected input string or byte for types.Bloom, decoding into (types.Receipts)[0](types.receiptRLP).Bloom"
 WARN [09-12|12:12:29.712] Receipt Correction: Failed to decode RLP receipts err="rlp: expected input string or byte for types.Bloom, decoding into (types.Receipts)[0](types.receiptRLP).Bloom"
 WARN [09-12|12:12:29.712] Receipt Correction: Failed to decode RLP receipts err="rlp: expected input string or byte for types.Bloom, decoding into (types.Receipts)[0](types.receiptRLP).Bloom"
 WARN [09-12|12:12:29.712] Receipt Correction: Failed to decode RLP receipts err="rlp: expected input string or byte for types.Bloom, decoding into (types.Receipts)[0](types.receiptRLP).Bloom"
 WARN [09-12|12:12:29.712] Receipt Correction: Failed to decode RLP receipts err="rlp: expected input string or byte for types.Bloom, decoding into (types.Receipts)[0](types.receiptRLP).Bloom"
 WARN [09-12|12:12:29.712] Receipt Correction: Failed to decode RLP receipts err="rlp: expected input string or byte for types.Bloom, decoding into (types.Receipts)[0](types.receiptRLP).Bloom"
 WARN [09-12|12:12:29.712] Receipt Correction: Failed to decode RLP receipts err="rlp: expected input string or byte for types.Bloom, decoding into (types.Receipts)[0](types.receiptRLP).Bloom"
 WARN [09-12|12:12:29.712] Receipt Correction: Failed to decode RLP receipts err="rlp: expected input string or byte for types.Bloom, decoding into (types.Receipts)[0](types.receiptRLP).Bloom"
 WARN [09-12|12:12:29.712] Receipt Correction: Failed to decode RLP receipts err="rlp: expected input string or byte for types.Bloom, decoding into (types.Receipts)[0](types.receiptRLP).Bloom"
 WARN [09-12|12:12:29.712] Receipt Correction: Failed to decode RLP receipts err="rlp: expected input string or byte for types.Bloom, decoding into (types.Receipts)[0](types.receiptRLP).Bloom"
 WARN [09-12|12:12:29.712] Receipt Correction: Failed to decode RLP receipts err="rlp: expected input string or byte for types.Bloom, decoding into (types.Receipts)[0](types.receiptRLP).Bloom"
 WARN [09-12|12:12:29.712] Receipt Correction: Failed to decode RLP receipts err="rlp: expected input string or byte for types.Bloom, decoding into (types.Receipts)[0](types.receiptRLP).Bloom"
 WARN [09-12|12:12:29.712] Receipt Correction: Failed to decode RLP receipts err="rlp: expected input string or byte for types.Bloom, decoding into (types.Receipts)[0](types.receiptRLP).Bloom"
```

#### Steps to reproduce the behaviour

Geth options

```
      --op-network="op-mainnet"
      --rollup.historicalrpc="https://mainnet.optimism.io"
      --rollup.sequencerhttp="https://mainnet-sequencer.optimism.io"
      --rollup.disabletxpoolgossip="true"
      --syncmode="snap"
      --state.scheme="path"
      --history.logs="0"
      --history.transactions="0"
```

op-node options

```
      op-node
      --network="op-mainnet"
      --syncmode="execution-layer"
      --l1.rpckind="standard"
      --l1.trustrpc
```

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

### PR DESCRIPTION
**Pull request by sebastianst**
**Description**

Deposit receipt correction got broken in a previous upstream merge (#638 #652) because upstream changed the way receipts are transferred during snap sync. They are now sent directly in their storage RLP. The upstream merge attempted to decode receipts into the `types.Receipts` slice, but because these are storage receipts, the bloom field is missing, so the `[]*types.ReceiptForStorage` type has to be used.

The receipt correction also got vastly optimized by only rlp-decoding if correction is actually necessary, which is almost never.

This PR also reduces the diff to upstream by removing unnecessary passing around and storage of the chain ID (it can be retrieved from the chain config).

**Tests**

Existing test got adapted. There was previously a copy-pasted test for the rlp and non-rlp version.

Also ran an internal snap-sync test, confirming that the warning logs are gone.

**Metadata**

Should fix https://github.com/ethereum-optimism/op-geth/issues/679

### CODE REVIEW

File: eth/downloader/downloader.go [hunk 1]
```diff
@@ -1058,7 +1053,11 @@ func (d *Downloader) commitSnapSyncData(results []*fetchResult, stateSync *state
 	receipts := make([]rlp.RawValue, len(results))
 	for i, result := range results {
 		blocks[i] = types.NewBlockWithHeader(result.Header).WithBody(result.body())
-		receipts[i] = correctReceiptsRLP(result.Receipts, result.Transactions, blocks[i].NumberU64(), d.chainID)
+		recs := result.Receipts
+		if !d.blockchain.Config().IsCanyon(blocks[i].Time()) {
```
Comment (axelKingsley) [inline eth/downloader/downloader.go]: nice ❤️

**Review by axelKingsley — APPROVED** [review]
Nice simplifications all around, thanks!

File: eth/downloader/downloader.go (hunk 1 above)
Comment (sebastianst) [reply eth/downloader/downloader.go]: 🌞 I actually updated this check to only run for Optimism-enabled chain, which is even more explicit
